DROP TABLE IF EXISTS VEHICLE;
 
CREATE TABLE VEHICLE (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  REGISTRATION_NUMBER VARCHAR(50) NOT NULL,
  MAKE VARCHAR(250) NOT NULL,
  MODEL VARCHAR(250) NOT NULL,
  FUEL VARCHAR(10) NOT NULL,
  CATEGORY VARCHAR(20) NOT NULL,
  PRICE_PER_DAY NUMERIC NOT NULL,
  CUSTOMER VARCHAR(50),
  HIRE_START_DATE DATE,
  HIRE_END_DATE DATE
);